apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: criteo-python-marketing-sdk
  description: Criteo Python Marketing SDK
  tags:
    - criteo
    - python
    - marketing
  annotations:
    backstage.io/techdocs-ref: github:https://github.com/criteo-dexter/criteo-python-marketing-sdk
    github.com/project-slug: criteo-dexter/criteo-python-marketing-sdk
    travis-ci.com/repo-slug: criteo-dexter/criteo-python-marketing-sdk
spec:
  type: service
  lifecycle: production
  owner: hellyeah@criteo.com
  implementsApis:
    - criteo-python-marketing-sdk
