apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: criteo-python-marketing-sdk
  description: Criteo Python Marketing SDK API
  tags:
    - criteo
    - python
    - marketing
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: dev-kit@criteo.com
  definition:
    $text: https://api.criteo.com/marketing/swagger/docs/v.1.0
